articles/urls.py
from django.urls import path, re_path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name = 'home'),    
    # URL Dispatcher
    # The different ways to retrieve user requests are as follows
    # Using the re_path module for regex
    # re_path(r'^(?P<slug>[\w-]+)/$', views.article_detail),
    # Using the Request converter built into Django - This is the one for me though
    path('<str:slug>/', views.article_detail, name = 'detail'),
]

django-origins/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('about/', views.about),
    path('', views.homepage),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

articles/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    # add in author

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse

# Create your views here.


def article_list(request):
    article = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles': article})


def article_detail(request, slug):
    # The below line of code simply returns the url in string format
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/detail.html', {'articles': article})

django-origins/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('Homepage')
    return render(request, "homepage.html")

def about(request):
    # return HttpResponse("About")
    return render(request, "about.html")

articles/templates/articles/article_list.html
{% extends 'articles/base.html' %} {% block content %} <div class="articles"> {% for article in articles %} <div
    class="article">
    <h2> <a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
    <p>{{ article.snippet }}</p>
    <p>{{ article.date }}</p>
  </div> {% endfor %} </div> {% endblock %}

articles/templates/articles/base.html
{% load static from static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

    <head>
        <meta charset="utf-8">
        <title>Articles</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>

    <body>
        <div id="brand"><a href="{% url 'articles:home' %}"><img src="{% static 'wolf.jpg' %}" alt="" class="brandImage"></a>
        </div>
        <div class="wrapper"> {% block content %} {% endblock %} </div>
    </body>

</html>

articles/templates/articles/detail.html
{% extends 'articles/base.html' %} {% block content %} <div class="detailcontent">
    <img src="{{ articles.thumb.url }}" alt="Thumbnail" width="100px" height="120px">
    <h2> {{ articles.title }} </h2>
    <p> {{ articles.body }} </p>
    <p> {{ articles.date }} </p>
</div>{% endblock %} 

templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About</title>
  </head>
  <body>
    <h1>About Us</h1>
    <p>We like Django</p>
  </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

  <head>
    <meta charset="utf-8">
    <title>Homepage</title>
  </head>

  <body>
    <h1>This is the homepage</h1>
    <p>Welcome to DjangoNautic</p>
  </body>

</html>